"""
templating/html_renderer.py
============================
Renders EmailVariant → HTML email using Jinja2 templates.
Three templates: reactivation / event / default (covers all other types).
"""

from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from core.types import CampaignBrief, EmailVariant

try:
    from jinja2 import Environment, BaseLoader
    JINJA_AVAILABLE = True
except ImportError:
    JINJA_AVAILABLE = False
    print("[html_renderer] jinja2 not installed — using string template fallback")


# ──────────────────────────────────────────────
# HTML Templates (inline, no file dependency)
# ──────────────────────────────────────────────

# Shared header/footer
_HEADER = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ subject_line }}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0f0f1a; font-family: 'Segoe UI', Arial, sans-serif; color: #e8e8f0; }
    .wrapper { max-width: 600px; margin: 0 auto; background: #1a1a2e; }
    .header { background: linear-gradient(135deg, {{ header_color1 }}, {{ header_color2 }}); padding: 40px 32px; text-align: center; }
    .game-badge { display: inline-block; background: rgba(255,255,255,0.15); color: #fff; font-size: 11px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; padding: 5px 14px; border-radius: 20px; margin-bottom: 16px; }
    .header h1 { color: #ffffff; font-size: 26px; font-weight: 800; line-height: 1.3; text-shadow: 0 2px 8px rgba(0,0,0,0.4); }
    .preheader-bar { background: {{ accent_color }}22; padding: 10px 32px; text-align: center; color: {{ accent_color }}; font-size: 13px; font-style: italic; }
    .body-section { padding: 32px; }
    .body-text { font-size: 15px; line-height: 1.8; color: #c8c8e0; white-space: pre-line; }
    .cta-section { text-align: center; padding: 24px 32px 36px; }
    .cta-btn { display: inline-block; background: linear-gradient(135deg, {{ accent_color }}, {{ header_color2 }}); color: #ffffff; font-size: 16px; font-weight: 700; text-decoration: none; padding: 16px 40px; border-radius: 8px; letter-spacing: 0.5px; box-shadow: 0 4px 20px {{ accent_color }}55; }
    .footer { background: #111120; padding: 20px 32px; text-align: center; }
    .footer p { font-size: 11px; color: #555570; line-height: 1.6; }
    .divider { height: 1px; background: linear-gradient(90deg, transparent, {{ accent_color }}44, transparent); margin: 0 32px; }
    .score-bar { background: #111120; padding: 12px 32px; display: flex; gap: 16px; justify-content: center; flex-wrap: wrap; }
    .score-pill { background: {{ accent_color }}22; color: {{ accent_color }}; font-size: 11px; font-weight: 600; padding: 4px 12px; border-radius: 12px; border: 1px solid {{ accent_color }}44; }
  </style>
</head>
<body>
<div class="wrapper">"""

_FOOTER = """  <div class="footer">
    <p>© 2025 {{ game }} · Tencent IEGG · <a href="#" style="color: #6060a0;">Unsubscribe</a> · <a href="#" style="color: #6060a0;">Privacy Policy</a><br>
    This email was generated by the CRM AI Email System (Capstone Demo).</p>
  </div>
</div>
</body>
</html>"""

TEMPLATE_BODY = _HEADER + """
  <div class="header">
    <div class="game-badge">{{ game }}</div>
    <h1>{{ subject_line }}</h1>
  </div>
  {% if preheader %}
  <div class="preheader-bar">{{ preheader }}</div>
  {% endif %}
  <div class="divider"></div>
  <div class="body-section">
    <div class="body-text">{{ body_text }}</div>
  </div>
  <div class="cta-section">
    <a href="#" class="cta-btn">{{ cta_text }}</a>
  </div>
  {% if show_scores and quality_score %}
  <div class="score-bar">
    <span class="score-pill">🎯 Relevance {{ "%.0f"|format(quality_score.relevance * 100) }}%</span>
    <span class="score-pill">🎭 Tone {{ "%.0f"|format(quality_score.tone * 100) }}%</span>
    <span class="score-pill">✅ Compliance {{ "%.0f"|format(quality_score.compliance * 100) }}%</span>
    <span class="score-pill">✨ Creativity {{ "%.0f"|format(quality_score.creativity * 100) }}%</span>
    <span class="score-pill">⭐ Overall {{ "%.0f"|format(quality_score.overall * 100) }}%</span>
  </div>
  {% endif %}
""" + _FOOTER


# Color themes per campaign type
CAMPAIGN_THEMES = {
    "reactivation":    ("#7c3aed", "#4f46e5", "#a78bfa"),   # purple
    "event_promotion": ("#dc2626", "#ea580c", "#fb923c"),   # red-orange
    "season_pass":     ("#0369a1", "#0284c7", "#38bdf8"),   # blue
    "vip_upgrade":     ("#92400e", "#b45309", "#fbbf24"),   # gold
    "new_content_drop":("#065f46", "#047857", "#34d399"),   # green
    "retention":       ("#1e3a5f", "#1d4ed8", "#60a5fa"),   # navy
}


class HTMLEmailRenderer:
    """Renders EmailVariant → HTML string using Jinja2 or string fallback."""

    def render(
        self,
        variant: EmailVariant,
        brief: CampaignBrief,
        show_scores: bool = True,
    ) -> str:
        campaign = brief.campaign_type.value
        c1, c2, accent = CAMPAIGN_THEMES.get(campaign, ("#4f46e5", "#7c3aed", "#a78bfa"))

        ctx = {
            "subject_line": variant.subject_line,
            "preheader": variant.preheader,
            "body_text": variant.body_text,
            "cta_text": variant.cta_text,
            "game": brief.game,
            "header_color1": c1,
            "header_color2": c2,
            "accent_color": accent,
            "show_scores": show_scores and variant.quality_score is not None,
            "quality_score": variant.quality_score,
        }

        if JINJA_AVAILABLE:
            env = Environment(loader=BaseLoader())
            tmpl = env.from_string(TEMPLATE_BODY)
            return tmpl.render(**ctx)
        else:
            return self._string_fallback(ctx)

    def _string_fallback(self, ctx: dict) -> str:
        """Minimal HTML without Jinja2."""
        qs = ctx.get("quality_score")
        score_html = ""
        if qs and ctx.get("show_scores"):
            score_html = f"""
            <p style="text-align:center;color:#aaa;font-size:12px;">
            Relevance: {qs.relevance:.0%} | Tone: {qs.tone:.0%} |
            Compliance: {qs.compliance:.0%} | Creativity: {qs.creativity:.0%} |
            Overall: {qs.overall:.0%}
            </p>"""
        return f"""<!DOCTYPE html><html><head><meta charset="UTF-8">
        <title>{ctx['subject_line']}</title></head>
        <body style="background:#0f0f1a;color:#e8e8f0;font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;">
        <div style="background:{ctx['header_color1']};padding:30px;text-align:center;border-radius:8px 8px 0 0;">
            <p style="color:#fff;font-size:11px;letter-spacing:2px;text-transform:uppercase;">{ctx['game']}</p>
            <h1 style="color:#fff;font-size:24px;">{ctx['subject_line']}</h1>
        </div>
        <div style="background:#1a1a2e;padding:24px;">
            <p style="color:#b0b0c8;font-style:italic;margin-bottom:16px;">{ctx['preheader']}</p>
            <p style="white-space:pre-line;line-height:1.8;">{ctx['body_text']}</p>
        </div>
        <div style="text-align:center;padding:24px;background:#1a1a2e;">
            <a href="#" style="background:{ctx['accent_color']};color:#fff;padding:14px 36px;border-radius:6px;text-decoration:none;font-weight:700;">{ctx['cta_text']}</a>
        </div>
        {score_html}
        <div style="background:#111;padding:16px;text-align:center;">
            <p style="color:#555;font-size:11px;">© 2025 {ctx['game']} · Tencent IEGG · <a href="#" style="color:#666;">Unsubscribe</a></p>
        </div>
        </body></html>"""
